server:
  port: 7001
ignore:
  urls:
  - /token/**
  - /mobile/**
  - /**/*.css
  - /auth/**
  - /refresh/**
  - /swagger-ui.html
  - /swagger-resources/**
  - /*/v2/api-docs
  - /webjars/**
---
spring:
  profiles: dev
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
---
spring:
  profiles: prod
eureka:
  instance:
    ip-address: 193.112.100.103
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://193.112.100.103:8761/eureka/
