server:
  port: 7001
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huarui1?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0  
ignore:
  urls:
  - /token/**
  - /mobile/**
  - /**/*.css
  - /auth/**
  - /refresh/**
  - /swagger-ui.html
  - /swagger-resources/**
  - /*/v2/api-docs
  - /webjars/**
---
spring:
  profiles: dev
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
---
spring:
  profiles: prod
eureka:
  instance:
    ip-address: 193.112.100.103
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://193.112.100.103:8761/eureka/
